version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development

  healthcheck:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    environment:
      # Use the service name "app" to reach the Flask container
      - HEALTH_ENDPOINT=http://app:8000/health
      - CHECK_INTERVAL=60
      - RESPONSE_THRESHOLD=3.0
      - RETRY_COUNT=3
      - RETRY_DELAY=2.0
