version: "3"

services:
  web:
    build: .
    ports:
      - '8000:8000'
    command: python health.py
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8000/health]
      interval: 30s
      timeout: 10s
      retries: 3

  health_checker:
    build: .
    depends_on:
      - web
    environment:
      - HEALTH_ENDPOINT=http://web:8000/health
      - CHECK_INTERVAL=60
      - RESPONSE_THRESHOLD=3.0
      - RETRY_COUNT=3
      - RETRY_DELAY=2.0
    command: python health_check.py
